CREATE OR REPLACE PROCEDURE PR_PRUEBA_ALL 
AS
  V_SQL VARCHAR2(2000);
BEGIN

  DBMS_OUTPUT.PUT_LINE('CREADO DE PROCEDIMIENTO DE INSERT A UNA TABLA');
  INSERT INTO WMONTANO.STG_PRUEBA VALUES('01-01-2022','KARLA PANOZO');
  
END;      

