CREATE OR REPLACE PROCEDURE PR_PRUEBA_ALL(FECHA VARCHAR2,NOMBRE VARCHAR2)
AS
 
BEGIN

  INSERT INTO WMONTANO.STG_PRUEBA VALUES(FECHA,NOMBRE);
  COMMIT;
  
  INSERT INTO WMONTANO.STG_PRUEBA_1
    SELECT FECHA,
          NOMMBRE  
    FROM WMONTANO.STG_PRUEBA;
    
    COMMIT;
  
END;      

